### ISSUE TITLE
Installation on MAC OSX error

### ISSUE THREAD

**Issue by rascyber** [galio-org/galio#204]
EthicalHacker:galio-starter-kit CyberDevelopment$ sudo npm install galio-framework
Password:
npm WARN peerDependencies The peer dependency react@* included from galio-framework will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-native@* included from galio-framework will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency react-native-vector-icons@>6.0.0 included from galio-framework will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> galio-framework@0.6.3 postinstall /Users/CyberDevelopment/ReactNative/galio-starter-kit/node_modules/galio-framework
> opencollective-postinstall

/Users/CyberDevelopment/ReactNative/galio-starter-kit/node_modules/galio-framework/node_modules/opencollective-postinstall/index.js:14
    console.log(`\u001b[96m\u001b[1mThank you for using ${pkg.name}!\u001b[96m
                ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 19.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "galio-framework"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! galio-framework@0.6.3 postinstall: `opencollective-postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the galio-framework@0.6.3 postinstall script 'opencollective-postinstall'.
npm ERR! This is most likely a problem with the galio-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     opencollective-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls galio-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/CyberDevelopment/ReactNative/galio-starter-kit/npm-debug.log
EthicalHacker:galio-starter-kit CyberDevelopment$ yarn add galio-framework
-bash: yarn: command not found
EthicalHacker:galio-starter-kit CyberDevelopment$

**Comment by palingheorghe** [comment]
Hi @rascyber ,

Thank you for this issue, we'll investigate further! 
Alin
